### PR TITLE
implementing a config object to specify meta data

### PR DESCRIPTION
**Pull request by mansona**

### CODE REVIEW

**Comment by rwwagner90** [comment]
@sivakumar-kailasam I'm curious what you think of this approach and if you have any ideas to make this generic and ergonomic to allow specifying keys for this data. I'm also open to moving away from mixins, if there is another way you have in mind. Let me know 😄

**Comment by mansona** [comment]
I agree with @sivakumar-kailasam that this is a good start 👍 this PR is just an extension of the "old architecture" and I think we should get it merged and spike out an experiment with some of the points regarding services and computed properties.

I think I quite like the idea of just extending the base service when you want to override how you get some info. Also, it would allow us to make this promise aware out of the box (I think)

**Comment by rwwagner90** [comment]
@mansona I implemented the service based approach, that @sivakumar-kailasam recommended. I believe it also solves this issue for you. Please take a look if you would like https://github.com/shipshapecode/ember-meta/pull/3

**Comment by snewcomer** [comment]
@rwwagner90 I'm seeing the headData service from `ember-cli-head` as the one that is being injected.  Removing their empty service the injects your service...

https://github.com/ronco/ember-cli-head/blob/master/app/services/head-data.js

**Pull request closed without merging**
